In [1]:
import pandas as pd
import numpy as np
np.random.seed(42)
import random
random.seed(42)
from project1 import defs

dim_reduced_train_features: pd.DataFrame = defs.load_asset_value("dim_reduced_train_features")
train: pd.DataFrame = defs.load_asset_value("train")
dim_reduced_test_features: pd.DataFrame = defs.load_asset_value("dim_reduced_test_features")
test: pd.DataFrame = defs.load_asset_value("test")

2024-04-13 11:43:55 -0700 - dagster - DEBUG - system - Loading file from: /home/maguire/ucla/ece219/project1/project1/../data/dim_reduced_train_features using PickledObjectFilesystemIOManager...
2024-04-13 11:43:55 -0700 - dagster - DEBUG - system - Loading file from: /home/maguire/ucla/ece219/project1/project1/../data/train using PickledObjectFilesystemIOManager...
2024-04-13 11:43:55 -0700 - dagster - DEBUG - system - Loading file from: /home/maguire/ucla/ece219/project1/project1/../data/dim_reduced_test_features using PickledObjectFilesystemIOManager...
2024-04-13 11:43:55 -0700 - dagster - DEBUG - system - Loading file from: /home/maguire/ucla/ece219/project1/project1/../data/test using PickledObjectFilesystemIOManager...


In [2]:
map_row_to_class = {
    0:"basketball",
    1:"baseball",
    2:"tennis",
    3:"football",
    4:"soccer",
    5:"forest fire",
    6:"flood",
    7:"earthquake",
    8:"drought",
    9:"heatwave"
}

In [3]:
from sklearn.multiclass import OneVsOneClassifier, OneVsRestClassifier
from sklearn.naive_bayes import GaussianNB

nb_1v1_clf = OneVsOneClassifier(GaussianNB())

In [4]:
nb_1v1_clf.fit(dim_reduced_train_features, train['leaf_label'])

OneVsOneClassifier(estimator=GaussianNB())

In [5]:
from project1.utils.MetricsAnalyzer import MetricsAnalyzer

In [6]:
nb_1v1_metrics = MetricsAnalyzer(nb_1v1_clf, dim_reduced_test_features, test['leaf_label'])
nb_1v1_metrics.print_all(roc=False)

Confusion Matrix: 
[[54  0  1  0  2  3  0  3  1 11]
 [ 2 76  0  0  0  5  0  0  1  6]
 [ 0  0 60  0  0  0  1  3  1  3]
 [ 0  0  1 43  0  0  0  0  0 10]
 [ 1  0  1  0 61  0  1  1  0  1]
 [ 0  1  0  0  0 50  0  0  8  2]
 [ 2  0  9  1  2  0 16 31  3  9]
 [ 1  0  5  0  4  1 25 19  1 11]
 [ 0  1  0  0  0  1  0  0 66  5]
 [ 6  0  0  0  2  0  0  1  3 57]]
Accuracy Score: 
0.7212643678160919
Recall Score: 


ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].